// <auto-generated />
using ContainerService.Core.Models;
using ContainerService.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ContainerService.Infrastructure.Migrations
{
    [DbContext(typeof(ContainerDbContext))]
    [Migration("20180516215641_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContainerService.Core.Models.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProductType");

                    b.Property<string>("SerialShippingContainerCode");

                    b.Property<Guid?>("ShipId");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("ContainerService.Core.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ContainerId");

                    b.Property<string>("Name");

                    b.Property<int>("ProductType");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ContainerService.Core.Models.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<Guid?>("ShipServiceId");

                    b.HasKey("Id");

                    b.HasIndex("ShipServiceId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("ContainerService.Core.Models.ShipService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ShipService");
                });

            modelBuilder.Entity("ContainerService.Core.Models.Truck", b =>
                {
                    b.Property<string>("LicensePlate")
                        .ValueGeneratedOnAdd();

                    b.HasKey("LicensePlate");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("ContainerService.Core.Models.Container", b =>
                {
                    b.HasOne("ContainerService.Core.Models.Ship")
                        .WithMany("Containers")
                        .HasForeignKey("ShipId");
                });

            modelBuilder.Entity("ContainerService.Core.Models.Product", b =>
                {
                    b.HasOne("ContainerService.Core.Models.Container")
                        .WithMany("Products")
                        .HasForeignKey("ContainerId");
                });

            modelBuilder.Entity("ContainerService.Core.Models.Ship", b =>
                {
                    b.HasOne("ContainerService.Core.Models.ShipService", "ShipService")
                        .WithMany()
                        .HasForeignKey("ShipServiceId");
                });
#pragma warning restore 612, 618
        }
    }
}
